version: '3'
services:
  redis-temp:
    image: redis:7.0.2-alpine
    command: redis-server --port 6379
    #    container_name: redis-temp
    hostname: redis-normal
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 36379:6379
    links:
      - redis-commander-temp
    networks:
      - default
      - my-network 
  redis-commander-temp:
    image: rediscommander/redis-commander:latest
    #    container_name: redis-commander
    hostname: redis-commander
    restart: always
    environment:
      - REDIS_HOSTS=redis-normal
    #      - REDIS_HOST=redis-normal:redis:16379
    ports:
      - 38081:8081
networks:
  my-network:
    driver: bridge